@extends('researcher.layout')
@section('content')
<div class="student-welcome"><div><p class="eyebrow">ESPACE CHERCHEUR</p><h1>Bonjour, {{ auth()->user()->name }}.</h1><p>Pilotez vos projets, publications et suivis scientifiques.</p></div></div>
<section class="student-grid">@foreach ([['Projets soumis', $stats['submitted_projects']], ['Brouillons', $stats['draft_projects']], ['En évaluation', $stats['evaluation_projects']], ['Projets acceptés', $stats['accepted_projects']], ['Projets rejetés', $stats['rejected_projects']], ['Projets financés', $stats['funded_projects']], ['Publications', $stats['publications']], ['Conventions actives', $stats['active_conventions']], ['Notifications non lues', $stats['unread_notifications']], ['Actions en attente', $stats['pending_actions']]] as [$label, $value])<article class="student-panel"><div class="stats-grid"><div><strong>{{ $value }}</strong><span>{{ $label }}</span></div></div></article>@endforeach</section>
<section class="student-grid"><article class="student-panel"><div class="panel-title"><h2>Situation financière</h2></div><div class="stats-grid"><div><strong>{{ number_format($stats['requested_amount'], 0, ',', ' ') }}</strong><span>Montant demandé ({{ $projects->first()->currency ?? 'GNF' }})</span></div><div><strong>{{ number_format($stats['awarded_amount'], 0, ',', ' ') }}</strong><span>Montant accordé</span></div><div><strong>{{ number_format($stats['disbursed_amount'], 0, ',', ' ') }}</strong><span>Montant décaissé</span></div></div></article></section>
<div class="student-grid"><section class="student-panel"><div class="panel-title"><h2>Mes projets</h2></div>@forelse($projects as $project)<div class="application-item"><div><small>{{ $project->reference }}</small><a href="{{ route('researcher.projects.show', $project->id) }}"><strong>{{ $project->title }}</strong></a></div><span>{{ ucfirst($project->status) }}</span></div>@empty<p>Aucun projet. Utilisez le formulaire pour créer un brouillon.</p>@endforelse
<form method="POST" action="{{ route('researcher.projects.create') }}" class="stack">@csrf<h3>Nouveau projet</h3><input name="title" placeholder="Titre du projet" required><textarea name="abstract" placeholder="Résumé scientifique"></textarea><input name="budget" type="number" min="0" step="0.01" placeholder="Budget"><button class="button button-lime">Créer le projet</button></form></section>
<section class="student-panel"><div class="panel-title"><h2>Nouvelle publication</h2></div><p>Les publications validées sont visibles dans la liste publique.</p><a class="button button-dark" href="{{ route('researcher.publications') }}">Gérer mes publications</a><h2>Profil</h2><p>{{ $profile?->research_domain ?: 'Votre domaine de recherche n’est pas encore renseigné.' }}</p><a href="{{ route('researcher.profile') }}">Compléter le profil →</a></section></div>
@endsection
