<!doctype html>
<html lang="fr">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{{ $title }} du FOSER."><title>{{ $title }} | FOSER</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body>
<header class="site-header"><div class="shell nav-wrap"><a class="brand" href="{{ route('home') }}"><span class="brand-mark">F</span><span><strong>FOSER</strong><small>Institution</small></span></a><nav class="main-nav"><a href="{{ route('home') }}">Accueil</a><a class="active" href="{{ route('institution.index') }}">Le FOSER</a><a href="{{ route('programs.index') }}">Nos programmes</a><a href="{{ route('calls.index') }}">Appels</a></nav><a class="button button-dark" href="{{ route('student.login') }}">Mon espace <span>↗</span></a></div></header>
<main><section class="page-hero"><div class="shell"><a class="text-link light" href="{{ route('institution.index') }}">← Le FOSER</a><div class="section-kicker" style="margin-top:28px"><span>INSTITUTION</span><span>FOSER</span></div><h1>{{ $title }}</h1></div></section><section class="shell section-pad">
@if(isset($content))<article class="content-columns"><div><h2>{{ $content->title ?? $title }}</h2></div><div class="lead">{!! nl2br(e($content->body ?? $content->summary ?? 'Le contenu sera publié prochainement depuis l’administration.')) !!}</div></article>
@elseif($section === 'valeurs')<div class="news-grid">@forelse($values as $value)<article class="student-panel"><span class="eyebrow">{{ $value->icon ?: 'FOSER' }}</span><h2>{{ $value->name }}</h2><p>{{ $value->description }}</p></article>@empty<p class="empty-state">Les valeurs institutionnelles seront publiées prochainement.</p>@endforelse</div>
@elseif(in_array($section, ['organigramme', 'conseil-administration', 'direction-generale', 'directions'], true))<div data-organization-tree class="organization-shell">@forelse($organization as $unit)@include('public.partials.organization-node', ['unit' => $unit])@empty<p class="empty-state">Aucune structure publiée.</p>@endforelse</div>
@elseif(in_array($section, ['documents', 'rapports-annuels'], true))<form method="GET" class="student-panel form-row" style="display:grid;grid-template-columns:2fr 1fr auto;gap:16px;margin-bottom:24px"><label>Recherche<input name="q" value="{{ request('q') }}" placeholder="Titre ou description"></label><label>Année<input name="year" type="number" value="{{ request('year') }}" min="1900" max="2100"></label><button class="button button-dark" type="submit">Filtrer</button></form><div class="news-grid">@forelse($documents as $document)<article class="student-panel"><span class="eyebrow">{{ $document->year ?: 'Document' }} · {{ $document->document_type }}</span><h2>{{ $document->title }}</h2><p>{{ $document->description }}</p><p>{{ $document->author ?: 'Source institutionnelle' }}</p><a class="button button-lime" href="{{ route('institution.documents.download', $document) }}">Télécharger <span>↓</span></a></article>@empty<p class="empty-state">Aucun document publié ne correspond à votre recherche.</p>@endforelse</div>{{ $documents->links() }}
@endif</section></main><footer class="footer"><div class="shell footer-bottom"><span>© {{ date('Y') }} FOSER · Tous droits réservés</span><a href="{{ route('institution.index') }}">Le FOSER</a></div></footer></body></html>
