<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $cms[$page.'.title']->title ?? ucfirst($page) }} | FOSER</title>@if (file_exists(public_path('build/manifest.json')) || file_exists(public_path('hot'))) @vite(['resources/css/app.css', 'resources/js/app.js']) @endif</head>
<body>
<div class="topline"><div class="shell top-inner"><span>RÉPUBLIQUE DU BURKINA FASO</span><a href="{{ url('/contact') }}">Nous contacter</a></div></div>
<header class="site-header"><div class="shell nav-wrap"><a class="brand" href="{{ url('/') }}"><span class="brand-mark">F</span><span><strong>FOSER</strong><small>Fonds de Soutien à l'Éducation<br>et à la Recherche</small></span></a><nav class="main-nav"><a href="{{ url('/') }}">{{ __('messages.home') }}</a><a href="{{ route('institution.index') }}">Le FOSER</a><a href="{{ route('programs.index') }}">{{ __('messages.programs') }}</a><a href="{{ url('/calls') }}">Appels à candidatures</a><a href="{{ url('/news') }}">Actualités</a></nav><x-language-switcher /><a class="button button-dark" href="{{ route('student.login') }}">{{ __('messages.login') }} <span>↗</span></a></div></header>
<main><section class="page-hero"><div class="shell"><div class="section-kicker"><span>FOSER</span><span>Portail institutionnel</span></div><h1>{{ $cms[$page.'.title']->title ?? ucfirst($page) }}</h1><p>{{ $cms[$page.'.intro']->body ?? 'Une information publique claire, des opportunités accessibles et un service au cœur des parcours.' }}</p></div></section><section class="shell section-pad content-page"><div class="section-kicker"><span>01</span><span>Informations officielles</span></div><div class="content-columns"><h2>{{ $cms[$page.'.heading']->title ?? 'Une institution au service des possibles.' }}</h2><div>@if(isset($cms[$page.'.body']))<div class="lead">{!! nl2br(e($cms[$page.'.body']->body)) !!}</div>@else<p class="lead">Cette page est en attente de publication depuis le back-office FOSER.</p>@endif</div></div></section></main>
<footer class="footer"><div class="shell footer-main"><div class="footer-brand"><a class="brand brand-light" href="{{ url('/') }}"><span class="brand-mark">F</span><span><strong>FOSER</strong><small>Fonds de Soutien à l'Éducation<br>et à la Recherche</small></span></a><p>{{ $cms['footer.tagline']->body ?? 'Construire les capacités. Faire grandir les possibles.' }}</p></div><div><h4>Navigation</h4><a href="{{ url('/about') }}">Le FOSER</a><a href="{{ route('programs.index') }}">Programmes</a><a href="{{ url('/calls') }}">Appels à candidatures</a></div><div><h4>Contact</h4><a href="{{ url('/contact') }}">{{ $cms['contact.email']->body ?? 'Nous contacter' }}</a></div></div><div class="shell footer-bottom"><span>© {{ date('Y') }} FOSER · Tous droits réservés</span><span>Burkina Faso</span></div></footer>
</body></html>
