<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{{ ucfirst($page) }} | FOSER, Fonds de Soutien à l'Éducation et à la Recherche.">
    <meta property="og:title" content="{{ ucfirst($page) }} | FOSER"><meta property="og:type" content="website"><meta property="og:url" content="{{ url('/'.$page) }}">
    <title>{{ ucfirst($page) }} | FOSER</title>
    @if (file_exists(public_path('build/manifest.json')) || file_exists(public_path('hot')))
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    @endif
</head>
<body>
    <div class="topline"><div class="shell top-inner"><span>RÉPUBLIQUE DU BURKINA FASO</span><span>La Patrie ou la Mort, nous Vaincrons</span><a href="{{ url('/contact') }}">Nous contacter</a></div></div>
    <header class="site-header"><div class="shell nav-wrap"><a class="brand" href="{{ url('/') }}"><span class="brand-mark">F</span><span><strong>FOSER</strong><small>Fonds de Soutien à l'Éducation<br>et à la Recherche</small></span></a><nav class="main-nav"><a href="{{ url('/') }}">Accueil</a><a href="{{ url('/about') }}">Le FOSER</a><a href="{{ url('/programs') }}">Nos programmes</a><a href="{{ url('/calls') }}">Appels à candidatures</a><a href="{{ url('/news') }}">Actualités</a><a href="{{ url('/documents') }}">Ressources</a></nav><a class="button button-dark" href="{{ route('student.login') }}">Espace étudiant <span>↗</span></a></div></header>
    <main><section class="page-hero"><div class="shell"><div class="section-kicker"><span>FOSER</span><span>Portail institutionnel</span></div><h1>{{ match ($page) { 'about' => 'Le FOSER', 'programs' => 'Nos programmes', 'calls' => 'Appels à candidatures', 'news' => 'Actualités', 'media' => 'Médiathèque', 'documents' => 'Centre documentaire', 'faq' => 'Questions fréquentes', 'contact' => 'Nous contacter', default => ucfirst($page) } }}</h1><p>Une information publique claire, des opportunités accessibles et un service au cœur des parcours.</p></div></section><section class="shell section-pad content-page"><div class="section-kicker"><span>01</span><span>Informations officielles</span></div><div class="content-columns"><h2>{{ match ($page) { 'about' => 'Une institution au service des possibles.', 'programs' => 'Accompagner chaque étape.', 'calls' => 'Les opportunités publiées par le Fonds.', 'news' => 'Les nouvelles de notre action.', 'media' => 'Images, voix et moments partagés.', 'documents' => 'Les ressources pour comprendre et avancer.', 'faq' => 'Les réponses aux questions essentielles.', 'contact' => 'Une équipe à votre écoute.', default => 'Le portail FOSER.' } }}</h2><div><p class="lead">Cette page est reliée au socle éditorial Laravel. Les contenus publiés, les documents et les opportunités seront administrés depuis le back-office FOSER.</p><div class="empty-state">Aucun contenu publié dans cette rubrique pour le moment.</div><a class="button button-dark" href="{{ url('/') }}">Retour à l'accueil <span>→</span></a></div></div></section></main><footer class="footer"><div class="shell footer-main"><div class="footer-brand"><a class="brand brand-light" href="{{ url('/') }}"><span class="brand-mark">F</span><span><strong>FOSER</strong><small>Fonds de Soutien à l'Éducation<br>et à la Recherche</small></span></a><p>Construire les capacités.<br>Faire grandir les possibles.</p></div><div><h4>Navigation</h4><a href="{{ url('/about') }}">Le FOSER</a><a href="{{ url('/programs') }}">Programmes</a><a href="{{ url('/calls') }}">Appels à candidatures</a></div><div><h4>Contact</h4><a href="{{ url('/contact') }}">Nous contacter</a><a href="https://wa.me/22600000000">WhatsApp ↗</a></div></div><div class="shell footer-bottom"><span>© {{ date('Y') }} FOSER · Tous droits réservés</span><span>Burkina Faso</span></div></footer>
</body>
</html>
