<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Tableau de bord étudiant | FOSER</title>@if (file_exists(public_path('build/manifest.json')) || file_exists(public_path('hot'))) @vite(['resources/css/app.css', 'resources/js/app.js']) @endif</head>
<body class="student-body">
<header class="student-header"><div class="shell nav-wrap"><a class="brand" href="{{ url('/') }}"><span class="brand-mark">F</span><span><strong>FOSER</strong><small>Espace étudiant</small></span></a><nav class="student-nav"><a class="active" href="{{ route('student.dashboard') }}">Tableau de bord</a><a href="{{ route('student.applications') }}">Mes dossiers</a><a href="{{ route('student.documents') }}">Pièces</a><a href="{{ route('student.payments') }}">Paiements</a><a href="{{ route('student.support') }}">Messages</a><a href="{{ route('student.profile') }}">Profil</a></nav><form method="POST" action="{{ route('auth.logout') }}">@csrf<button class="button button-dark" type="submit">Déconnexion</button></form></div></header>
<main class="shell student-main"><div class="student-welcome"><div><p class="eyebrow">ESPACE ÉTUDIANT</p><h1>Bonjour, {{ auth()->user()->name }}.</h1><p>Suivez vos demandes, vos pièces et vos versements depuis un seul espace.</p></div><a class="button button-lime" href="{{ route('student.applications') }}">Créer une demande <span>+</span></a></div>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<section class="student-grid">
@foreach ([['Demandes', $stats['total']], ['En cours', $stats['active']], ['Acceptées', $stats['accepted']], ['Rejetées', $stats['rejected']], ['Paiements reçus', $stats['payments']], ['Notifications non lues', $stats['unread']], ['Pièces manquantes', $stats['missing']]] as [$label, $value])<article class="student-panel"><div class="stats-grid"><div><strong>{{ $value }}</strong><span>{{ $label }}</span></div></div></article>@endforeach
</section>
<section class="student-grid"><article class="student-panel"><div class="panel-title"><h2>Dernières demandes</h2><a href="{{ route('student.applications') }}">Voir tout</a></div>@forelse($applications->take(5) as $application)<div class="application-item"><div><small>{{ $application->reference }}</small><strong>{{ \App\Enums\StudentApplicationStatus::tryFrom($application->status)?->label() ?? ucfirst($application->status) }}</strong></div><span>{{ \App\Enums\StudentApplicationStatus::tryFrom($application->status)?->progress() ?? 0 }} %</span></div>@empty<p class="student-empty">Aucune demande pour le moment.</p>@endforelse</article><article class="student-panel"><div class="panel-title"><h2>Paiements reçus</h2><a href="{{ route('student.payments') }}">Voir tout</a></div>@forelse($payments->take(4) as $payment)<div class="application-item"><div><strong>{{ number_format($payment->amount, 0, ',', ' ') }} GNF</strong><small>{{ $payment->program_name ?: 'Programme' }} · {{ $payment->provider_reference ?: 'Référence en attente' }}</small></div><span>{{ ucfirst($payment->status) }}</span></div>@empty<p class="student-empty">Aucun paiement enregistré.</p>@endforelse</article></section>
<section class="student-panel"><div class="panel-title"><h2>Opportunités</h2><a href="{{ url('/calls') }}">Découvrir les appels</a></div><div class="opportunity-list">@forelse($calls as $call)<a href="{{ url('/calls') }}"><span class="opportunity-date">{{ \Carbon\Carbon::parse($call->closes_at)->format('d.m.Y') }}</span><strong>{{ $call->title }}</strong><span>↗</span></a>@empty<p class="student-empty">Aucun appel ouvert.</p>@endforelse</div></section></main></body></html>
