<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Programmes | FOSER</title>@if (file_exists(public_path('build/manifest.json')) || file_exists(public_path('hot'))) @vite(['resources/css/app.css', 'resources/js/app.js']) @endif</head>
<body class="student-body">
<header class="student-header"><div class="shell nav-wrap"><a class="brand" href="{{ url('/') }}"><x-site-logo-mark /><span><strong>FOSER</strong><small>Espace étudiant</small></span></a><nav class="student-nav"><a href="{{ route('student.dashboard') }}">Tableau de bord</a><a class="active" href="{{ route('student.programs') }}">Programmes</a><a href="{{ route('student.applications') }}">Mes dossiers</a><a href="{{ route('student.notifications') }}">Notifications</a><a href="{{ route('student.profile') }}">Profil</a></nav><form method="POST" action="{{ route('auth.logout') }}">@csrf<button class="button button-dark" type="submit">Déconnexion</button></form></div></header>
<main class="shell student-main"><div class="student-welcome"><div><p class="eyebrow">PROGRAMMES FOSER</p><h1>Les dispositifs ouverts.</h1><p>Explorez les programmes publiés et préparez votre candidature avec les informations officielles.</p></div></div>
<section class="student-panel form-panel"><form method="GET" class="form-row"><label>Rechercher<input name="q" value="{{ request('q') }}" placeholder="Nom ou description"></label><label>Type<select name="type"><option value="">Tous les types</option><option value="education" @selected(request('type') === 'education')>Éducation</option><option value="loan" @selected(request('type') === 'loan')>Prêt</option><option value="research" @selected(request('type') === 'research')>Recherche</option><option value="innovation" @selected(request('type') === 'innovation')>Innovation</option></select></label><button class="button button-dark" type="submit">Filtrer</button></form></section>
<section class="student-grid">@forelse($programs as $program)<article class="student-panel"><p class="eyebrow">{{ ucfirst($program->type) }}</p><h2>{{ $program->name }}</h2><p>{{ $program->description ?: 'Programme FOSER publié.' }}</p><p><strong>{{ $program->budget ? number_format($program->budget, 0, ',', ' ').' '.$program->currency : 'Montant selon étude du dossier' }}</strong></p><p>{{ $program->starts_at ? \Carbon\Carbon::parse($program->starts_at)->format('d/m/Y') : 'Date à confirmer' }} au {{ $program->ends_at ? \Carbon\Carbon::parse($program->ends_at)->format('d/m/Y') : 'date de clôture à confirmer' }}</p><div class="application-actions"><a class="button button-dark" href="{{ route('student.programs.eligibility', $program->id) }}">Vérifier l’éligibilité</a><a class="button button-lime" href="{{ route('student.applications.create-form', $program->id) }}">Voir les détails <span>→</span></a></div></article>@empty<div class="student-panel student-empty">Aucun programme publié ne correspond à votre recherche.</div>@endforelse</section>{{ $programs->links() }}</main>
</body></html>
