<!doctype html>
<html lang="fr">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nos programmes | FOSER</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body>
<div class="topline"><div class="shell top-inner"><span>RÉPUBLIQUE DU BURKINA FASO</span><a href="{{ url('/contact') }}">Nous contacter</a></div></div>
<header class="site-header"><div class="shell nav-wrap"><a class="brand" href="{{ route('home') }}"><x-site-logo-mark /><span><strong>FOSER</strong><small>Fonds de Soutien à l'Éducation<br>et à la Recherche</small></span></a><nav class="main-nav" aria-label="Navigation principale"><a href="{{ route('home') }}">Accueil</a><a class="active" href="{{ route('programs.index') }}">Nos programmes</a><a href="{{ route('calls.index') }}">Appels</a><a href="{{ route('researcher.register') }}">Créer un compte chercheur</a></nav><a class="button button-dark" href="{{ route('student.login') }}">Mon espace <span>↗</span></a></div></header>
<main><section class="page-hero"><div class="shell"><div class="section-kicker"><span>FOSER</span><span>Parcours et opportunités</span></div><h1>Nos programmes</h1><p>Découvrez les dispositifs du FOSER et accédez directement aux conditions, montants, procédures et opportunités adaptées à votre parcours.</p></div></section>
<section class="shell section-pad"><div class="program-grid">@foreach($catalog as $index => $program)<article class="program-card {{ ['program-main','program-research','program-innovation'][$index % 3] }}"><span class="card-number">{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</span><div><span class="card-label">FOSER</span><h2>{{ $program['title'] }}</h2><p>{{ $program['description'] }}</p>@foreach($program['links'] as $slug => $label)<a href="{{ route('programs.section', [$program['slug'], $slug]) }}" style="display:block;margin-top:10px">{{ $label }} <span>↗</span></a>@endforeach</div></article>@endforeach</div></section></main>
<footer class="footer"><x-site-partners-footer /><div class="shell footer-bottom"><span>© {{ date('Y') }} FOSER · Tous droits réservés</span><a href="{{ route('home') }}">Accueil</a></div></footer>
</body></html>
