<!doctype html>
<html lang="fr">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $sectionTitle }} | FOSER</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body>
<header class="site-header"><div class="shell nav-wrap"><a class="brand" href="{{ route('home') }}"><span class="brand-mark">F</span><span><strong>FOSER</strong><small>Fonds de Soutien à l'Éducation<br>et à la Recherche</small></span></a><nav class="main-nav"><a href="{{ route('home') }}">Accueil</a><a class="active" href="{{ route('programs.index') }}">Nos programmes</a><a href="{{ route('calls.index') }}">Appels</a><a href="{{ route('researcher.register') }}">Créer un compte chercheur</a></nav><a class="button button-dark" href="{{ route('student.login') }}">Mon espace <span>↗</span></a></div></header>
<main><section class="page-hero"><div class="shell"><a class="text-link light" href="{{ route('programs.index') }}">← Nos programmes</a><div class="section-kicker" style="margin-top:28px"><span>{{ strtoupper(str_replace('-', ' ', $category)) }}</span><span>Dispositif FOSER</span></div><h1>{{ $sectionTitle }}</h1></div></section>
<section class="shell section-pad">
@if($category === 'prets-etudes' && $section === 'simulation')
<div class="content-columns"><div><h2>Simulez votre prêt.</h2><p class="lead">Renseignez le montant, la durée et le taux pour obtenir une estimation immédiate.</p></div><form class="student-panel form-panel" method="POST" action="{{ route('programs.loan.simulate') }}" data-loan-simulation>@csrf<label>Montant souhaité<input name="amount" type="number" min="1" value="500000" required></label><label>Durée (mois)<input name="duration_months" type="number" min="1" max="120" value="24" required></label><label>Taux annuel (%)<input name="interest_rate" type="number" min="0" max="100" step="0.01" value="5" required></label><label>Différé (mois)<input name="grace_period_months" type="number" min="0" max="24" value="0"></label><button class="button button-lime" type="submit">Calculer</button><div data-simulation-result class="notice" hidden></div></form></div>
@elseif($category === 'recherche' && $section === 'appels')
<form method="GET" class="student-panel form-row" style="display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:16px;margin-bottom:24px"><label>Recherche<input name="q" value="{{ request('q') }}" placeholder="Titre ou référence"></label><label>Domaine<input name="domain" value="{{ request('domain') }}" placeholder="Domaine"></label><label>Année<input name="year" type="number" value="{{ request('year') }}"></label><button class="button button-dark" type="submit">Filtrer</button></form><div class="call-list">@forelse($data['calls'] as $call)<a class="call-row" href="{{ route('calls.show', $call->id) }}"><span class="call-date">{{ $call->closes_at ? \Carbon\Carbon::parse($call->closes_at)->format('d.m.Y') : 'À venir' }}</span><span><small>{{ $call->reference }} · {{ $call->domains ?: 'Recherche' }}</small><strong>{{ $call->title }}</strong></span><span class="arrow">↗</span></a>@empty<p class="empty-state">Aucun appel à projets publié.</p>@endforelse</div>{{ $data['calls']->links() }}
@elseif($category === 'recherche' && $section === 'projets-finances')
<form method="GET" class="student-panel form-row" style="display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:16px;margin-bottom:24px"><label>Recherche<input name="q" value="{{ request('q') }}" placeholder="Titre ou résumé"></label><label>Domaine<input name="domain" value="{{ request('domain') }}" placeholder="Domaine"></label><label>Année<input name="year" type="number" value="{{ request('year') }}"></label><button class="button button-dark" type="submit">Filtrer</button></form><div class="news-grid">@forelse($data['projects'] as $project)<article class="student-panel"><span class="eyebrow">{{ $project->reference }} · {{ $project->year ?: 'Année non renseignée' }}</span><h2>{{ $project->title }}</h2><p>{{ $project->abstract ?: 'Projet de recherche financé par le FOSER.' }}</p><p><strong>Domaine :</strong> {{ $project->domain ?: $project->research_area ?: 'Non renseigné' }}<br><strong>Porteur :</strong> {{ $project->researcher_name ?: 'Non renseigné' }}<br><strong>Établissement :</strong> {{ $project->university_name ?: 'Non renseigné' }}<br><strong>Montant :</strong> {{ ($project->funded_amount ?: $project->budget) ? number_format($project->funded_amount ?: $project->budget, 0, ',', ' ').' '.$project->currency : 'Non renseigné' }}</p><a class="button button-lime" href="{{ route('programs.project', $project->id) }}">Voir le projet <span>→</span></a></article>@empty<p class="empty-state">Aucun projet financé n’est actuellement publié.</p>@endforelse</div>{{ $data['projects']->links() }}
@elseif($section === 'faq')
<div class="content-columns"><div><h2>Questions fréquentes</h2><p class="lead">Trouvez les réponses validées par le FOSER.</p><form method="GET" class="form-panel"><label>Rechercher une réponse<input name="q" value="{{ request('q') }}" placeholder="Votre question"></label><button class="button button-dark" type="submit">Rechercher</button></form></div><div>@forelse($data['faqs'] as $faq)<details class="student-panel" style="margin-bottom:12px"><summary><strong>{{ $faq->question }}</strong></summary><p>{{ $faq->answer }}</p></details>@empty<p class="empty-state">Aucune réponse ne correspond à votre recherche.</p>@endforelse</div></div>
@else
<form method="GET" class="student-panel form-row" style="display:grid;grid-template-columns:2fr 1fr auto;gap:16px;margin-bottom:24px"><label>Recherche<input name="q" value="{{ request('q') }}" placeholder="Nom ou description"></label><label>Année<input name="year" type="number" value="{{ request('year') }}"></label><button class="button button-dark" type="submit">Filtrer</button></form><div class="news-grid">@forelse($data['items'] as $item)<article class="student-panel"><span class="eyebrow">{{ $item->program_name }}</span><h2>{{ $item->name ?? $item->research_area ?? $item->innovation_area }}</h2><p>{{ $item->description ?? $item->conditions ?? $item->eligibility ?? 'Informations détaillées à consulter dans la fiche du programme.' }}</p>@if($item->maximum_amount ?? null)<p><strong>Montant maximal :</strong> {{ number_format($item->maximum_amount, 0, ',', ' ') }}</p>@endif@if($item->beneficiaries ?? null)<p><strong>Bénéficiaires :</strong> {{ $item->beneficiaries }}</p>@endif@if($item->procedure ?? null)<p><strong>Procédure :</strong> {{ $item->procedure }}</p>@endif@if($category === 'recherche' && $section === 'financement')<a class="button button-lime" href="{{ route('programs.research-funding.detail', ['category' => $category, 'section' => $section, 'item' => $item->id]) }}">Voir le financement <span>→</span></a>@elseif($category === 'innovation')<a class="button button-lime" href="{{ route('programs.innovation.detail', ['category' => $category, 'section' => $section, 'item' => $item->id]) }}">Voir le dispositif <span>→</span></a>@endif</article>@empty<p class="empty-state">Aucun dispositif n’est actuellement publié dans cette rubrique.</p>@endforelse</div>{{ $data['items']->links() }}
@endif
</section></main>
<footer class="footer"><div class="shell footer-bottom"><span>© {{ date('Y') }} FOSER · Tous droits réservés</span><a href="{{ route('programs.index') }}">Nos programmes</a></div></footer>
<script>document.querySelector('[data-loan-simulation]')?.addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget; const result = form.querySelector('[data-simulation-result]'); const response = await fetch(form.action, { method: 'POST', headers: {'X-CSRF-TOKEN': form.querySelector('[name=_token]').value, 'Accept': 'application/json'}, body: new FormData(form) }); const data = await response.json(); if (!response.ok) { result.hidden = false; result.textContent = 'Veuillez vérifier les paramètres saisis.'; return; } result.hidden = false; result.textContent = `Mensualité estimée : ${Number(data.monthly_payment).toLocaleString('fr-FR')} · Intérêts : ${Number(data.total_interest).toLocaleString('fr-FR')} · Total : ${Number(data.total_repayment).toLocaleString('fr-FR')}`; });</script>
</body></html>
